import { StyleSheet } from "react-native"

export const globalStyles = StyleSheet.create({
    tela: {
        flex: 1,
        justifyContent: "flex-start",
    },
    text: {
        color: "white",
    },
    navMain: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingTop: 50,
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    navSecondary: {
        position: "fixed",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 20,
        paddingTop: 50,
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    navScrolled: {
        backgroundColor: "#202020ff",
        shadowColor: "#000000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 8,
    },
    navContainer: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: 20,
    },
    navText: {
        color: "white",
        fontSize: 20,
        fontWeight: "bold",
    },
    form: {
        display: "flex",
        flexDirection: "column",
        gap: 20,
        marginTop: 20,
        marginBottom: 30,
        paddingHorizontal: 20,
    },
    inputImage: {
        width: 160,
        height: 160,
        borderRadius: 16,
        backgroundColor: "#1c1c1e",
        borderWidth: 1,
        borderColor: "#333",
        overflow: "hidden",
        justifyContent: "center",
        alignItems: "center",
    },
    label: {
        display: "flex",
        flexDirection: "column",
        gap: 10,
    },
    labelText: {
        color: "#BFBFBF",
    },
    labelInput: {
        color: "white",
        paddingTop: 14,
        paddingBottom: 14,
        paddingHorizontal: 18,
        borderRadius: 5,
        fontSize: 16,
        borderStyle: "solid",
        borderWidth: 2,
        borderColor: "#404040",
    },
    labelCategory: {
        color: "white",
        borderRadius: 5,
        fontSize: 16,
        borderStyle: "solid",
        borderWidth: 2,
        borderColor: "#404040",
    },
    inputFocused: {
        borderColor: "#FF922B",
    },
    addGoal: {
        textAlign: "center",
        position: "absolute",
        right: 20,
        bottom: 20,
        backgroundColor: "#FF922B",
        color: "black",
        padding: 10,
        fontSize: 24,
        borderRadius: 50,
        width: 56,
        height: 56,
    },
    noGoalsWrapper: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    noGoals: {
        color: "#BFBFBF",
        fontSize: 18,
        position: "absolute",
        top: "50%",
        left: "50%",
        transform: [{ translateX: -120 }, { translateY: -50 }],
    },
    item: {
        marginVertical: 15,
        display: "flex",
        flexDirection: "row",
        gap: 20,
        paddingHorizontal: 20,
    },
    goalCover: {
        width: 120,
        height: 120,
        borderRadius: 16,
    },
    content: {
        flex: 1,
        flexDirection: "column",
        justifyContent: "space-between",
    },
    goalText: {
        color: "white",
        fontSize: 18,
        marginBottom: 8,
    },
    daysLeft: {
        color: "#BFBFBF",
        fontSize: 12,
    },
    progress: {
        display: "flex",
        flexDirection: "column",
        gap: 4,
        marginTop: 12,
    },
    progressText: {
        color: "#BFBFBF",
        fontSize: 13,
        textAlign: "right",
    },
    progressBar: {
        height: 5,
        width: "100%",
        backgroundColor: "#404040",
        alignSelf: "flex-end",
        borderRadius: 4,
        marginTop: 4,
    },
    progressLevel: {
        height: "100%",
        backgroundColor: "#FF922B",
        borderRadius: 4,
    },
    expiredView: {
        height: 30,
        flexDirection: "row",
        width: 93,
        alignItems: "center",
        gap: 6,
        borderWidth: 1,
        borderColor: "#FF922B",
        borderRadius: 333,
        paddingHorizontal: 12,
    },
    expiredText: {
        color: "#FF922B",
        fontSize: 11,
        fontWeight: "bold",
    },
    navGoal: {
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 20,
        marginBottom: 30,
        paddingTop: 50,
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    goalCoverView: {
        flexDirection: "column",
        gap: 20,
        alignItems: "center",
    },
    goalView: {
        flex: 1,
        flexDirection: "column",
        justifyContent: "space-between",
        paddingBottom: 20,
        paddingHorizontal: 20,
    },
    goalContext: {
        flexDirection: "column",
        gap: 60,
    },
    goalImage: {
        width: 140,
        height: 140,
        borderRadius: 16,
    },
    goal: {
        fontSize: 24,
        color: "white",
        textAlign: "center",
    },
    goalInfo: {
        flexDirection: "column",
        gap: 25,
    },
    goalLabel: {
        flexDirection: "column",
        gap: 4,
    },
    goalLabelText: {
        color: "#BFBFBF",
        fontSize: 16,
    },
    goaltext: {
        color: "white",
        fontSize: 16,
    },
    editCategory: {
        color: "white",
        textTransform: "capitalize",
    },
    goalEditButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        borderColor: "#bfbfbf57",
        borderWidth: 1,
        color: "white",
        padding: 6,
        fontSize: 16,
        borderRadius: 60,
        textAlign: "center",
    },

    buttonText: {
        color: "#FF922B",
        fontSize: 15,
    },
})
